-- =============================================================
-- SIMULADOR DE EVALUACIÓN DOCENTE - SUPABASE
-- Control de un único dispositivo/sesión activa por participante
-- Ejecutar TODO este archivo una sola vez en Supabase > SQL Editor.
-- =============================================================

create extension if not exists unaccent with schema extensions;

create table if not exists public.participantes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null,
  activo boolean not null default true,
  session_token uuid,
  session_last_seen timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists participantes_correo_unique
  on public.participantes (lower(trim(correo)));

create table if not exists public.resultados (
  id bigint generated by default as identity primary key,
  participante_id bigint not null references public.participantes(id) on delete cascade,
  fecha timestamptz not null default now(),
  modalidad text not null,
  correctas integer not null,
  incorrectas integer not null,
  sin_responder integer not null,
  total integer not null,
  porcentaje numeric(5,2) not null,
  tiempo_segundos integer not null,
  escala integer,
  envio_automatico boolean not null default false
);

-- Las tablas NO se exponen directamente al navegador.
alter table public.participantes enable row level security;
alter table public.resultados enable row level security;
revoke all on table public.participantes from anon, authenticated;
revoke all on table public.resultados from anon, authenticated;
revoke all on sequence public.participantes_id_seq from anon, authenticated;
revoke all on sequence public.resultados_id_seq from anon, authenticated;

-- -------------------------------------------------------------
-- LOGIN ATÓMICO
-- Si existe una sesión con actividad en los últimos 3 minutos,
-- otro dispositivo no puede entrar con el mismo usuario.
-- -------------------------------------------------------------
create or replace function public.login_participante(
  p_nombre text,
  p_correo text,
  p_session_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_user public.participantes%rowtype;
begin
  select * into v_user
  from public.participantes
  where activo = true
    and extensions.unaccent(lower(trim(regexp_replace(nombre, '\\s+', ' ', 'g')))) =
        extensions.unaccent(lower(trim(regexp_replace(p_nombre, '\\s+', ' ', 'g'))))
    and lower(trim(correo)) = lower(trim(p_correo))
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'code', 'INVALID');
  end if;

  if v_user.session_token is not null
     and v_user.session_token <> p_session_token
     and v_user.session_last_seen is not null
     and v_user.session_last_seen > now() - interval '3 minutes' then
    return jsonb_build_object('ok', false, 'code', 'BUSY');
  end if;

  update public.participantes
     set session_token = p_session_token,
         session_last_seen = now()
   where id = v_user.id;

  return jsonb_build_object(
    'ok', true,
    'code', 'OK',
    'user', jsonb_build_object(
      'id', v_user.id,
      'nombre', v_user.nombre,
      'correo', v_user.correo
    )
  );
end;
$$;

-- Mantiene viva la sesión. Devuelve false si la sesión ya no pertenece
-- a este dispositivo o fue reemplazada/expiró.
create or replace function public.heartbeat_participante(p_session_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_updated integer;
begin
  update public.participantes
     set session_last_seen = now()
   where activo = true
     and session_token = p_session_token;
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

-- Cierre de sesión inmediato.
create or replace function public.logout_participante(p_session_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_updated integer;
begin
  update public.participantes
     set session_token = null,
         session_last_seen = null
   where session_token = p_session_token;
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

-- Guarda el resultado centralmente en Supabase.
create or replace function public.guardar_resultado(
  p_session_token uuid,
  p_modalidad text,
  p_correctas integer,
  p_incorrectas integer,
  p_sin_responder integer,
  p_total integer,
  p_porcentaje numeric,
  p_tiempo_segundos integer,
  p_escala integer,
  p_envio_automatico boolean
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_participante_id bigint;
begin
  select id into v_participante_id
  from public.participantes
  where activo = true
    and session_token = p_session_token
    and session_last_seen > now() - interval '5 minutes';

  if v_participante_id is null then
    return false;
  end if;

  insert into public.resultados(
    participante_id, modalidad, correctas, incorrectas, sin_responder,
    total, porcentaje, tiempo_segundos, escala, envio_automatico
  ) values (
    v_participante_id, p_modalidad, p_correctas, p_incorrectas, p_sin_responder,
    p_total, p_porcentaje, p_tiempo_segundos, p_escala, p_envio_automatico
  );

  update public.participantes
     set session_last_seen = now()
   where id = v_participante_id;

  return true;
end;
$$;

-- Solo estas funciones pueden ser invocadas desde la clave pública.
revoke all on function public.login_participante(text,text,uuid) from public;
revoke all on function public.heartbeat_participante(uuid) from public;
revoke all on function public.logout_participante(uuid) from public;
revoke all on function public.guardar_resultado(uuid,text,integer,integer,integer,integer,numeric,integer,integer,boolean) from public;

grant execute on function public.login_participante(text,text,uuid) to anon;
grant execute on function public.heartbeat_participante(uuid) to anon;
grant execute on function public.logout_participante(uuid) to anon;
grant execute on function public.guardar_resultado(uuid,text,integer,integer,integer,integer,numeric,integer,integer,boolean) to anon;

-- Usuario inicial. Si ya existe por correo, actualiza sus datos.
insert into public.participantes(nombre, correo, activo)
values ('Rita', 'pintadorita3@gmail.com', true)
on conflict ((lower(trim(correo)))) do update
set nombre = excluded.nombre,
    activo = true;

-- Consultas útiles para el administrador (se ejecutan SOLO en SQL Editor):
-- Ver usuarios y estado de sesión:
-- select id,nombre,correo,activo,session_last_seen,
--        (session_last_seen > now() - interval '3 minutes') as conectado
-- from public.participantes order by id;
--
-- Agregar otro usuario:
-- insert into public.participantes(nombre,correo) values ('Nombre','correo@ejemplo.com');
--
-- Liberar manualmente una sesión bloqueada:
-- update public.participantes set session_token=null, session_last_seen=null
-- where lower(correo)=lower('correo@ejemplo.com');
--
-- Ver resultados:
-- select r.fecha,p.nombre,p.correo,r.modalidad,r.correctas,r.total,r.porcentaje,r.tiempo_segundos,r.escala
-- from public.resultados r join public.participantes p on p.id=r.participante_id
-- order by r.fecha desc;
